# Configurações para deploy na Netlify

[build]
  # Diretório que será publicado. Como todos os nossos arquivos estão na raiz,
  # definimos como ".", que representa o diretório atual.
  publish = "."